async function enviarScript(scriptText){
	const lines = scriptText.split(/[\n\t]+/).map(line => line.trim()).filter(line => line);
	main = document.querySelector("#main"),
	textarea = main.querySelector(`div[contenteditable="true"]`)
	
	if(!textarea) throw new Error("Não há uma conversa aberta")
	
	for(const line of lines){
		console.log(line)
	
		textarea.focus();
		document.execCommand('insertText', false, line);
		textarea.dispatchEvent(new Event('change', {bubbles: true}));
	
		setTimeout(() => {
			(main.querySelector(`[data-testid="send"]`) || main.querySelector(`[data-icon="send"]`)).click();
		}, 100);
		
		if(lines.indexOf(line) !== lines.length - 1) await new Promise(resolve => setTimeout(resolve, 250));
	}
	
	return lines.length;
}

enviarScript(`

BOLSONARO NA CADEIA, VAMOS LER AQUI PARA VOSSA SENHORIA A SENTENÇA FINAL!
BOLSONARO NA CADEIA, VAMOS LER AQUI PARA VOSSA SENHORIA A SENTENÇA FINAL!
BOLSONARO NA CADEIA, VAMOS LER AQUI PARA VOSSA SENHORIA A SENTENÇA FINAL!
BOLSONARO NA CADEIA, VAMOS LER AQUI PARA VOSSA SENHORIA A SENTENÇA FINAL!
BOLSONARO NA CADEIA, VAMOS LER AQUI PARA VOSSA SENHORIA A SENTENÇA FINAL!

AÇÃO PENAL 2.668 DISTRITO FEDERAL RELATOR : MIN. ALEXANDRE DE
MORAES AUTOR(A/S)(ES) : MINISTÉRIO PÚBLICO FEDERAL PROC.(A/S)(ES) : PROCURADOR-GERAL DA
REPÚBLICA RÉU(É)(S) : ALEXANDRE RAMAGEM RODRIGUES ADV.(A/S) : PAULO RENATO
GARCIA CINTRA PINTO RÉU(É)(S) : ANDERSON GUSTAVO TORRES ADV.(A/S) :
EUMAR ROBERTO NOVACKI ADV.(A/S) : ALINE FERREIRA DOS SANTOS RÉU(É)(S)
: AUGUSTO HELENO RIBEIRO PEREIRA ADV.(A/S) : MATHEUS MAYER MILANEZ
RÉU(É)(S) : JAIR MESSIAS BOLSONARO ADV.(A/S) : CELSO SANCHEZ VILARDI
E OUTRO(A/S) ADV.(A/S) : SAULO LOPES SEGALL ADV.(A/S) : PAULO
AMADOR THOMAZ ALVES DA CUNHA BUENO (147616 SP OAB) RÉU(É)(S)
: MAURO CESAR BARBOSA CID ADV.(A/S) : RAFAEL MIRANDA MENDONCA
ADV.(A/S) : CEZAR ROBERTO BITENCOURT ADV.(A/S) : JAIR ALVES PEREIRA
ADV.(A/S) : VANIA BARBOSA ADORNO BITENCOURT RÉU(É)(S) : PAULO SERGIO
NOGUEIRA DE OLIVEIRA ADV.(A/S) : ANDREW FERNANDES FARIAS RÉU(É)(S) :
ALMIR GARNIER SANTOS ADV.(A/S) : DEMÓSTENES LÁZARO XAVIER TORRES E
OUTRO(A/S) RÉU(É)(S) : WALTER SOUZA BRAGA NETTO ADV.(A/S) : RODRIGO
NASCIMENTO DALL ACQUA E OUTRO(A/S) ADV.(A/S) : JOSE LUIS MENDES
DE OLIVEIRA LIMA AUT. POL. : POLÍCIA FEDERAL DECISÃO Trata-se
de ação penal autuada em face de ALEXANDRE RAMAGEM RODRIGUES,
ALMIR GARNIER SANTOS, ANDERSON Documento assinado digitalmente conforme MP n°
2.200-2/2001 de 24/08/2001. O documento pode ser acessado pelo endereço
http://www.stf.jus.br/portal/autenticacao/autenticarDocumento.asp sob o código AB3D-1F0C-9157-7772 e senha EACD-0972-CA68-05DF AP 2668
/ DF 2 GUSTAVO TORRES, AUGUSTO HELENO RIBEIRO PEREIRA, JAIR
MESSIAS BOLSONARO, MAURO CÉSAR BARBOSA CID, PAULO SÉRGIO NOGUEIRA DE
OLIVEIRA e WALTER SOUZA BRAGA NETTO. Em 10/6/2025, encerrados os
interrogatórios de todos os réus, as partes foram intimadas para
eventuais requerimentos e diligências complementares, nos termos do art. 402,
do Código de Processo Penal, e do art. 10, da
Lei nº 8.038/90. A Procuradoria-Geral da República informou que não
possui diligências adicionais a serem produzidas nos autos (eDoc. 1.113).
O réu colaborador MAURO CÉSAR BARBOSA CID requereu “a prorrogação
do prazo para análise do conjunto probatório, em especial, das
mídias e arquivos digitais”. Formulou, ainda, os seguintes requerimentos (eDoc.
1.101): “(a) A expedição de ofício à ABIN – Agência
Brasileira de Inteligência, a fim de determinar que essa envie
à essa Corte, os relatórios de inteligência e demais dados
de informações obtidos pela Agência até o dia 8 de
janeiro de 2023, relativamente aos acampamentos e aos manifestantes que
lá ainda estavam. (b) A expedição de ofício à Subsecretaria
de Operações Integradas do Distrito Federal, a fim de determinar
que essa envie à essa Corte, Atas de reuniões realizadas
na Secretaria, relatórios e demais dados de informações obtidos até
o dia 8 de janeiro de 2023, relativamente aos acampamentos
e aos manifestantes que lá ainda estavam”. A Defesa de
ALEXANDRE RODRIGUES RAMAGEM não se manifestou. A Defesa de ALMIR
GARNIER SANTOS, ao argumento de que o réu foi inquirido
“sobre o deslocamento de blindados militares na Esplanada Documento assinado
digitalmente conforme MP n° 2.200-2/2001 de 24/08/2001. O documento pode
ser acessado pelo endereço http://www.stf.jus.br/portal/autenticacao/autenticarDocumento.asp sob o código AB3D-1F0C-9157-7772 e
senha EACD-0972-CA68-05DF AP 2668 / DF 3 dos Ministérios, em
agosto de 2021”, requereu que “se oficie ao Comando de
Operações Navais da Marinha do Brasil, ou à autoridade que
entender competente, para que informe, com a máxima precisão, a
data em que foi expedida a Diretiva (Ordem de Movimento)
relativa à Operação Formosa 2021, cuja execução se deu no
mês de agosto daquele ano”. Subsidiariamente, requereu que “o ofício
seja remetido ao Ministério da Defesa, para igual finalidade, a
fim de garantir a obtenção célere da informação” (eDoc. 1.080).
A Defesa de ANDERSON GUSTAVO TORRES afirmou a necessidade de
acareação entre o réu e a testemunha General Freire Gomes,
alegando que “especificamente no que tange a ANDERSON TORRES, o
depoimento de FREIRE GOMES está recheado de contradições, ao passo
que as declarações prestadas pela testemunha, talvez até pelo cansaço
(foram 11 horas de depoimento), e pelo acusado divergem frontalmente
em ponto nevrálgico do processo”. Alegou, também, que “em uma
simples busca no site google com a expressão “conjur/dl”, é
possível encontrar, até o dia de hoje, minuta de conteúdo
idêntico àquela encontrada na residência de ANDERSON TORRES, razão pela
qual argumenta a necessidade de expedição de ofício à empresa
Google Brasil Internet Ltda. para informar os dados do responsável
pela inserção. Por fim, ressaltou a necessidade de produção prova
pericial para “demonstrar que o conteúdo da minuta do “Google”
encontrada na casa de ANDERSON TORRES não tem qualquer semelhança
com os demais documentos supostamente antidemocráticos mencionados durante a instrução”,
bem como a necessidade de perícia audiovisual no vídeo da
live ocorrida em 29/7/2021. Assim, foram formulados os seguintes requerimentos
(eDoc. 1.094): “a) com lastro no art. 229 do CPP,
o deferimento do pedido de acareação entre a testemunha FREIRE
GOMES e ANDERSON TORRES ou, subsidiariamente, que o General FREIRE
GOMES seja reinquirido; Documento assinado digitalmente conforme MP n° 2.200-2/2001
de 24/08/2001. O documento pode ser acessado pelo endereço http://www.stf.jus.br/portal/autenticacao/autenticarDocumento.asp
sob o código AB3D-1F0C-9157-7772 e senha EACD-0972-CA68-05DF AP 2668 /
DF 4 b) a expedição de ofício à empresa Google
Brasil Internet (CNPJ: 06.990.590/0001-23, matriz localizada em São Paulo, na
Avenida Brigadeiro Faria Lima), para que informe os dados do
responsável pela inserção da minuta, que decreta Estado de Defesa,
em domínio público; c) o deferimento do exame pericial, com
a finalidade de demonstrar que o conteúdo da minuta encontrada
na casa de ANDERSON TORRES não tem qualquer semelhança com
os demais documentos supostamente antidemocráticos mencionados durante a instrução; d)
o deferimento de perícia audiovisual, a fim de que trechos
do relatório encaminhado pela Polícia Federal (e-DOC 611 - páginas
139 e 140, parte dos itens "1" e "2" do
tópico "Considerações e sugestões"; páginas 99 e 100, parte do
item "5" e a integralidade do item "14" do tópico
"Considerações finais"; e página 128, item "5" do tópico "Considerações
e conclusões") sejam devidamente comparados com a fala de ANDERSON
TORRES durante a live ocorrida em 29/07/2021”. A Defesa de
AUGUSTO HELENO RIBEIRO PEREIRA, ao argumento de que é impossível
a análise de todo o material fornecido pela Polícia Federal
em tempo hábil à apresentação das alegações finais, requereu “seja
determinado à Polícia Federal que apresente o material catalogado, ou,
ao menos, com um índice que torne possível a respectiva
análise” (eDoc. 1.109). Por sua vez, a Defesa de JAIR
MESSIAS BOLSONARO requereu a “a reabertura do prazo previsto nos
arts. 402 do CPP e 10 da Lei 8.038/90 após
manifestação do d. Procurador-Geral da República e do corréu delator”,
ressaltando que o réu delatado tem o direito de falar
por último. Destacou, ainda, que “o prejuízo na aplicação do
prazo comum também no presente caso, no qual há delator,
restou evidenciado pelas últimas movimentações processuais”, uma vez que, a
imprensa divulgou troca de Documento assinado digitalmente conforme MP n°
2.200-2/2001 de 24/08/2001. O documento pode ser acessado pelo endereço
http://www.stf.jus.br/portal/autenticacao/autenticarDocumento.asp sob o código AB3D-1F0C-9157-7772 e senha EACD-0972-CA68-05DF AP 2668
/ DF 5 mensagens realizada pelo réu colaborador MAURO CÉSAR
BARBOSA CID acerca de seu acordo de colaboração. Requereu, assim,
“a rescisão e anulação do acordo de delação premiada do
corréu Mauro Cid, reiterando-se aqui o pedido formulado na defesa
prévia”. Subsidiariamente, na hipótese de não ser acolhido o pedido
de rescisão e anulação do acordo de colaboração premiada, requereu
expedição de ofício à Meta Platforms Inc. para fornecer as
seguintes informações sobre a conta “@gabrielar702” e/ou “Gabriela R”: “(i)
todos os dados cadastrais do usuário; (ii) o IP e
porta lógica, data, horário e geolocalização da conexão utilizada para
a criação de referido perfil; (iii) histórico de acessos ao
perfil, incluindo acessos via aplicativo móvel, navegador web ou qualquer
outro meio, contendo endereço IP e porta lógica de origem,
datas, horários e geolocalização; (iv) informações sobre os dispositivos nos
quais a conta esteve ou está logada; (v) dados fornecidos
para recuperação da conta, incluindo e-mails alternativos e números de
telefones; (vi) outras contas do Instagram e de outras redes
sociais da empresa Meta logadas no mesmo celular, com os
respectivos dados e metadados, incluindo Facebook, Messenger e WhatsApp; (vii)
outros perfis que compartilham os dados ou elementos cadastrais vinculados
à conta analisada (como e- mail, telefone e IP de
criação); (viii) os dados e o conteúdo das mensagens enviadas
e recebidas no período de 1º de maio de 2023
a 13 de junho de 2025; Documento assinado digitalmente conforme
MP n° 2.200-2/2001 de 24/08/2001. O documento pode ser acessado
pelo endereço http://www.stf.jus.br/portal/autenticacao/autenticarDocumento.asp sob o código AB3D-1F0C-9157-7772 e senha EACD-0972-CA68-05DF
AP 2668 / DF 6 (ix) informações sobre métodos de
pagamento cadastrados e eventuais transações realizadas na plataforma; (x) todas
as informações coletadas sobre o conteúdo criado pela conta “@gabrielar702”,
inclusive posts, comentários, áudios, o conteúdo fornecido por meio do
recurso de câmera; (i) os metadados sobre o conteúdo e
mensagens, incluindo local e data; (ii) o horário, a frequência
e a duração das atividades do usuário indicado; (iii) eventuais
fotos ou vídeos fornecidos para obter suporte para a conta”
A Defesa de JAIR MESSIAS BOLSONARO, também, requereu a “reabertura
do prazo para requerimento de diligências depois de a empresa
Meta prestar as informações requeridas e depois da manifestação da
PGR e do delator” e que “seja concedido o acesso
integral aos dados obtidos por meio de quebras de sigilo
telemático (de dados armazenados em nuvens) no âmbito dos autos
do Inq 4878 e da Pet 10.405” (eDoc. 1.082). A
Defesa de PAULO SÉRGIO NOGUEIRA DE OLIVEIRA requereu a juntada
de documentos (eDoc. 1.085). A Defesa de WALTER SOUZA BRAGA
NETTO requereu que “seja designada audiência para realização de acareação
entre o corréu delator Mauro Cid e o Gen. Braga
Netto, a fim de que sejam dirimidas as divergências entre
as declarações por eles prestadas em interrogatório judicial”, alegando que
“os interrogatórios do corréu delator Mauro Cid e do Requerente
contêm divergências entre si”. Ressaltou, ainda, que “a abertura de
prazo para alegações finais nesta ação penal antes do interrogatório
dos corréus nos processos relativos aos demais núcleos impedirá a
análise de relevantes provas que certamente interferem no julgamento da
presente causa”, e também requereu o “compartilhamento das provas a
serem produzidas naqueles autos como emprestadas neste feito, com a
Documento assinado digitalmente conforme MP n° 2.200-2/2001 de 24/08/2001. O
documento pode ser acessado pelo endereço http://www.stf.jus.br/portal/autenticacao/autenticarDocumento.asp sob o código
AB3D-1F0C-9157-7772 e senha EACD-0972-CA68-05DF AP 2668 / DF 7 consequente
suspensão do curso desta AP 2668 até a finalização da
instrução dos demais núcleos”. Por fim, requereu “a concessão de
no mínimo 30 dias para análise do material fornecido pela
Polícia Federal, com posterior devolução do prazo do art. 402
do CPP”, salientando que “pretende-se que a concessão de acesso
ao material probatório seja efetiva para garantia a ampla defesa
e o contraditório, e não apenas um acesso formal e
protocolar” (eDoc. 1.103). É o relatório. DECIDO. I) REQUERIMENTOS PROTELATÓRIOS,
IRRELEVANTES OU IMPERTINENTES AO ATUAL MOMENTO PROCESSUAL. O atual estágio
processual destina-se, nos termos do art. 402 do Código de
Processo Penal e no artigo 10 da Lei 8.038/90, a
oportunizar às partes, no prazo conjunto de 5 (cinco) dias,
a realização de diligências imprescindíveis que tenham como circunstâncias ou
fatos apurados na instrução criminal, cujo deferimento deve ser precedido
da demonstração da sua necessidade: AP 1513 (Rel. Min. ALEXANDRE
DE MORAES, Pleno, DJe de 2/10/2024); AP 1514 (Rel. Min.
ALEXANDRE DE MORAES, Pleno, DJe de 16/4/4024); AP 1515 (Rel.
Min. ALEXANDRE DE MORAES, Pleno, DJe de 30/9/2024); AP 1516
(Rel. Min. ALEXANDRE DE MORAES, Pleno, DJe de 19/9/2024); AP
1517 (Rel. Min. ALEXANDRE DE MORAES, Pleno, DJe de 19/4/2024);
AP 1578 (Rel. Min. ALEXANDRE DE MORAES, Pleno, DJe de
1º/4/2025); AP 2330 (Rel. Min. ALEXANDRE DE MORAES, Pleno, DJe
de 3/4/2025); AP 2333 (Rel. Min. ALEXANDRE DE MORAES, Pleno,
DJe de 26/3/2025); AP 2337 (Rel. Min. ALEXANDRE DE MORAES,
Pleno, DJe de 14/11/2024); AP 2405 (Rel. Min. ALEXANDRE DE
MORAES, Pleno, DJe de 10/10/2024); AP 2519 (Rel. Min. ALEXANDRE
DE MORAES, Primeira Turma, DJe de 12/03/2025); AP 2524 (Rel.
Min. ALEXANDRE DE MORAES, Primeira Turma, DJe de 12/03/2025); AP
2528(Rel. Min. ALEXANDRE DE MORAES, Primeira Turma, DJe de 12/03/2025);
AP 2540 (Rel. Min. ALEXANDRE DE MORAES, Primeira Turma, DJe
de 06/05/2025); AP 2545 (Rel. Min. ALEXANDRE DE Documento assinado
digitalmente conforme MP n° 2.200-2/2001 de 24/08/2001. O documento pode
ser acessado pelo endereço http://www.stf.jus.br/portal/autenticacao/autenticarDocumento.asp sob o código AB3D-1F0C-9157-7772 e
senha EACD-0972-CA68-05DF AP 2668 / DF 8 MORAES, Primeira Turma,
DJe de 21/03/2025); AP 2550 (Rel. Min. ALEXANDRE DE MORAES,
Primeira Turma, DJe de 28/02/2025); AP 2551 (Rel. Min. ALEXANDRE
DE MORAES, Primeira Turma, DJe de 12/03/2025); AP 2558 (Rel.
Min. ALEXANDRE DE MORAES, Primeira Turma, DJe de 12/03/2025); AP
2560 (Rel. Min. ALEXANDRE DE MORAES, Primeira Turma, DJe de
28/02/2025); AP 2572 (Rel. Min. ALEXANDRE DE MORAES, Primeira Turma,
DJe de 21/03/2025). Dessa maneira, o atual momento processual é
absolutamente inadequado para PEDIDOS PROTELATÓRIOS, CARACTERIZADOS POR REPETIÇÃO DE PEDIDOS
INDEFERIDOS ANTERIORMENTE, conforme decisões dos dias 17/5/2025 e 5/6/2025 (eDocs.
682, 945 e 951), como os pedidos de “prorrogação do
prazo para análise do conjunto probatório, em especial, das mídias
e arquivos digitais”(Defesa de MAURO BARBOSA CID), apresentação de “material
catalogado, ou, ao menos, com um índice que torne possível
a respectiva análise” (Defesa de AUGUSTO HELENO RIBEIRO PEREIRA), concessão
de no mínimo de 30 dias para análise do material
fornecido pela Polícia Federal (Defesa de WALTER SOUZA BRAGA NETTO)
-, ou REQUERIMENTOS IMPERTINENTES À FINALIDADE DO ARTIGO 402 DO
CÓDIGO DE PROCESSO PENAL, tais como, pedidos de anulação da
colaboração premiada e “a reabertura do prazo previsto nos arts.
402 do CPP e 10 da Lei 8.038/90 após manifestação
do d. Procurador- Geral da República e do corréu delator”
(Defesa de JAIR MESSIAS BOLSONARO) e suspensão da ação penal
até instrução de outras ações penais (Defesa de WALTER SOUZA
BRAGA NETTO). Da mesma maneira, REQUERIMENTO IMPERTINENTE E IRRELEVANTE, de
caráter MERAMENTE PROCRASTINATÓRIO, tal como, “seja concedido o acesso integral
aos dados obtidos por meio de quebras de sigilo telemático
(de dados armazenados em nuvens) no âmbito dos autos do
Inq 4878 e da Pet 10.405” (Defesa de JAIR MESSIAS
BOLSONARO), deve ser afastado, pois as referidas investigações - cujos
autos são públicos - NÃO SÃO OBJETO DA PRESENTE AÇÃO
PENAL, referindo-se a “investigação onde a Polícia Federal identificou a
constituição de uma associação Documento assinado digitalmente conforme MP n°
2.200-2/2001 de 24/08/2001. O documento pode ser acessado pelo endereço
http://www.stf.jus.br/portal/autenticacao/autenticarDocumento.asp sob o código AB3D-1F0C-9157-7772 e senha EACD-0972-CA68-05DF AP 2668
/ DF 9 criminosa para consecução de um fim comum,
qual seja, a prática dos crimes de inserção de dados
falsos de vacinação contra a Covid-19 nos sistema SIPNI e
RNDS do Ministério da Saúde” (PET 10405) e a inquérito
instaurado para apurar autoria da quebra de sigilo do Inquérito
policial 1361/2018 (INQ 4878). Nessas hipóteses, compete ao Juízo processante,
nos termos do art. 400, § 1º, do Código de
Processo Penal, INDEFERIR os pedidos e as diligências consideradas irrelevantes,
impertinentes ou protelatórias (HC 135.133-AgR/DF, Rel. Min. ROBERTO BARROSO, Primeira
Turma, DJe de 1º/2/2017; RHC 126.853-AgR/SP, Rel. Min. LUIZ FUX,
Primeira Turma, DJe de 15/9/2015; HC 96.421/PI, Rel. Min. TEORI
ZAVASCKI, Segunda Turma, DJe de 23/10/2014; AP 2417 AgR-quinto, Rel.
Min. ALEXANDRE DE MORAES, Primeira Turma, DJe de 7/3/2025). II)
REQUERIMENTOS PERTINENTES AO ATUAL MOMENTO PROCESSUAL. II.1) ACAREAÇÕES. A Defesa
de ANDERSON GUSTAVO TORRES afirmou a necessidade de acareação entre
o réu e a testemunha General Freire Gomes, alegando que
“especificamente no que tange a ANDERSON TORRES, o depoimento de
FREIRE GOMES está recheado de contradições, ao passo que as
declarações prestadas pela testemunha, talvez até pelo cansaço (foram 11
horas de depoimento), e pelo acusado divergem frontalmente em ponto
nevrálgico do processo”. A Defesa de WALTER SOUZA BRAGA NETTO,
por sua vez, requereu “seja designada audiência para realização de
acareação entre o corréu delator Mauro Cid e o Gen.
Braga Netto, a fim de que sejam dirimidas as divergências
entre as declarações por eles prestadas em interrogatório judicial”, alegando
que “os interrogatórios do corréu delator Mauro Cid e do
Requerente contêm divergências entre si”. Documento assinado digitalmente conforme MP
n° 2.200-2/2001 de 24/08/2001. O documento pode ser acessado pelo
endereço http://www.stf.jus.br/portal/autenticacao/autenticarDocumento.asp sob o código AB3D-1F0C-9157-7772 e senha EACD-0972-CA68-05DF AP
2668 / DF 10 Conforme salientando anteriormente nos interrogatórios dos
réus, o direito de permanecer em silêncio e a não
produzir provas contra si mesmo, à luz do disposto no
art. 5º, LXIII, da Constituição da República, apresenta-se como verdadeiro
complemento ao princípio do due process of law e da
ampla defesa, sem que por ele possa ser responsabilizado, inclusive
por depoimentos ou acareações mentirosas, uma vez que não se
conhece em nosso ordenamento jurídico o crime de perjúrio. Enquanto
conjunto institucionalizado de direitos e garantias do ser humano, que
tem por finalidade básica o respeito a sua dignidade, por
meio de sua proteção contra o arbítrio do poder estatal
e o estabelecimento de condições mínimas de vida e desenvolvimento
da personalidade humana, os direitos humanos fundamentais entre eles o
direito ao silêncio e a não autoincriminação caracterizam-se pela irrenunciabilidade
(HC 115830 MC, Relator: Min. GILMAR MENDES, DJe de 26/11/2012).
A participação do indivíduo na persecução penal não é apenas
um meio de assegurar que os fatos relevantes sejam trazidos
à tona e os argumentos pertinentes considerados, mais do que
isso, o direito de manifestar-se livremente e de ser ouvido
no momento processual adequado é intrínseco à natureza do julgamento,
cujo principal propósito é justificar o veredicto final, inclusive para
o próprio acusado, como resultado legal justamente obtido, concedendo-lhe o
respeito e a consideração que qualquer cidadão merece, preservando a
impossibilidade de alguém ser obrigado a produzir provas contra si
mesmo, seja em suas declarações, seja na compulsoriedade de entrega
de provas com potencial lesivo à sua defesa na persecução
penal, como salienta T.R.S. ALLAN (Constitucional Justice. Oxford: University Press,
2006, p. 12 e ss.). O privilégio contra a autoincriminação
(“privilege against self- incrimination”) tornou-se tema obrigatório a ser respeitado
em relação ao direito constitucional à ampla defesa, sendo direcionado
no intuito de Documento assinado digitalmente conforme MP n° 2.200-2/2001
de 24/08/2001. O documento pode ser acessado pelo endereço http://www.stf.jus.br/portal/autenticacao/autenticarDocumento.asp
sob o código AB3D-1F0C-9157-7772 e senha EACD-0972-CA68-05DF AP 2668 /
DF 11 preservar o caráter voluntário das manifestações do réu
e a regularidade de seu julgamento, com um diálogo equitativo
entre o indivíduo e o Estado, como bem salientado pelo
citado professor da Universidade de Cambridge. Esse diálogo equitativo entre
o indivíduo e o Estado pressupõe absoluto respeito à dignidade
da pessoa, a possibilidade de acesso à defesa técnica, com
a participação do advogado em seu interrogatório, principalmente a ausência
de qualquer tipo de coação ou indução nas declarações do
investigado, por parte do comportamento de autoridades públicas. O caráter
voluntário de suas manifestações na ótica de um diálogo equitativo
entre o indivíduo e o Estado permite ao acusado exercer
livre e discricionariamente o privilégio contra a autoincriminação, podendo, inclusive,
optar pelas previsões legais que autorizem benefícios à sua confissão
voluntária ou adesão às hipóteses de colaborações premiadas e outras
hipóteses de auxílio à Justiça. São suas opções e de
sua defesa técnica. Será o investigado quem escolherá livremente o
“direito de auxiliar no momento adequado”. Dessa maneira, também nas
acareações, o réu - diferentemente das testemunhas - não tem
o compromisso de dizer a verdade, podendo inclusive falseá-la em
prol de sua autodefesa. Entretanto, nos termos do artigo 229
do Código de Processo Penal, ressaltando, novamente, a advertência de
que o réu não tem o compromisso de dizer a
verdade na acareação, em PROL DA AMPLA DEFESA deve ser
autorizada a realização da acareação entre o réu WALTER SOUZA
BRAGA NETTO e o réu colaborador MAURO CÉSAR BARBOSA CID
e entre o réu ANDERSON GUSTAVO TORRES e a testemunha
MARCO ANTONIO FREIRE GOMES. II.2) REQUERIMENTOS PERTINENTES E DEVIDAMENTE JUSTIFICADOS.
A Defesa de ALMIR GARNIER SANTOS requereu que “se oficie
ao Documento assinado digitalmente conforme MP n° 2.200-2/2001 de 24/08/2001.
O documento pode ser acessado pelo endereço http://www.stf.jus.br/portal/autenticacao/autenticarDocumento.asp sob o
código AB3D-1F0C-9157-7772 e senha EACD-0972-CA68-05DF AP 2668 / DF 12
Comando de Operações Navais da Marinha do Brasil, ou à
autoridade que entender competente, para que informe, com a máxima
precisão, a data em que foi expedida a Diretiva (Ordem
de Movimento) relativa à Operação Formosa 2021, cuja execução se
deu no mês de agosto daquele ano” e, subsidiariamente, requereu
que “o ofício seja remetido ao Ministério da Defesa, para
igual finalidade, a fim de garantir a obtenção célere da
informação” (eDoc. 1.080). Observa-se que o pedido formulado por ALMIR
GARNIER SANTOS tem pertinência com os fatos decorrentes da instrução
processual, tendo inclusive a própria defesa ressaltado que a Operação
Formosa 2021 foi objeto de questionamento durante o interrogatório do
réu, razão pela qual defiro o requerimento. A Defesa de
ANDERSON GUSTAVO TORRES requereu a expedição de ofício à empresa
Google Brasil Internet “para que informe os dados do responsável
pela inserção da minuta, que decreta Estado de Defesa, em
domínio público”. Nesse sentido, solicitou “exame pericial, com a finalidade
de demonstrar que o conteúdo da minuta encontrada na casa
de ANDERSON TORRES não tem qualquer semelhança com os demais
documentos supostamente antidemocráticos mencionados durante a instrução” e realização de
“perícia audiovisual, a fim de que trechos do relatório encaminhado
pela Polícia Federal (...) sejam devidamente comparados com a fala
de ANDERSON TORRES durante a live ocorrida em 29/07/2021” (eDoc.
1.094). Constata-se que as diligências complementares decorrem de instrução processual,
considerando que as minutas de Golpe de Estado descritas na
acusação foram objeto de indagação de testemunhas e dos réus,
o que demonstram a pertinência do requerimento Com relação à
realização de perícia audiovisual para análise de comparação com a
fala do réu ANDERSON GUSTAVO TORRES durante a live ocorrida
em 29/7/2021, também verifica-se pertinência na diligência requerida, considerando que
esses fatos também foram objeto de questionamento durante a instrução
processual. Da mesma maneira, deve ser deferido o requerimento de
juntada de documentos formulado pela Defesa de PAULO SÉRGIO NOGUEIRA
DE Documento assinado digitalmente conforme MP n° 2.200-2/2001 de 24/08/2001.
O documento pode ser acessado pelo endereço http://www.stf.jus.br/portal/autenticacao/autenticarDocumento.asp sob o
código AB3D-1F0C-9157-7772 e senha EACD-0972-CA68-05DF AP 2668 / DF 13
OLIVERA, uma vez que, nos termos do art. 231 do
Código de Processo Penal, salvo os casos expressos em lei,
as partes poderão apresentar documentos em qualquer fase do processo.
III. PEDIDOS PREJUDICADOS. O réu colaborador MAURO CÉSAR BARBOSA CID
formulou pedidos de expedição de ofício à ABIN – Agência
Brasileira de Inteligência para encaminhar “os relatórios de inteligência e
demais dados de informações obtidos pela Agência até o dia
8 de janeiro de 2023, relativamente aos acampamentos e aos
manifestantes que lá ainda estavam”e de expedição de ofício à
Subsecretaria de Operações Integradas do Distrito Federal para enviar “Atas
de reuniões realizadas na Secretaria, relatórios e demais dados de
informações obtidos até o dia 8 de janeiro de 2023,
relativamente aos acampamentos e aos manifestantes que lá ainda estavam”
(eDoc. 1.101). Verifica-se que os documentos requeridos pela Defesa de
MAURO CÉSAR BARBOSA CID estão juntados aos autos da AP
2417, no eDoc. 1.211 e eDoc. 1336. Destaco, ainda, que
a AP 2417 é pública, havendo total e plena possibilidade
de acesso pelo réu colaborador MAURO CÉSAR BARBOSA CID; bem
como, que deferi o acesso integral do material apreendido pela
Polícia Federal, inclusive da AP 2417, em 30/4/2025, tendo determinado
o imediato envio do link externo para os e-mails dos
advogados dos réus - no caso do réu colaborador: Cezar
Roberto Bittencourt, OAB/RS 11.483 e OAB/DF 20.151 e-mail: cezar@cezarbitencourt.adv.br -;
em 12/5/2025 (eDoc. 583), razão pela qual há prejuízo do
pedido formulado pela Defesa MAURO CÉSAR BARBOSA CID. A Defesa
de JAIR MESSIAS BOLSONARO requereu a expedição de ofício à
META PLATFORMS INC. para fornecimento de informações sobre a conta
“@gabrielar702” e/ou “Gabriela R”. Da mesma forma, a Defesa de
WALTER SOUZA BRAGA NETTO também reiterou os termos do pedido
para expedição de ofício à META Documento assinado digitalmente conforme
MP n° 2.200-2/2001 de 24/08/2001. O documento pode ser acessado
pelo endereço http://www.stf.jus.br/portal/autenticacao/autenticarDocumento.asp sob o código AB3D-1F0C-9157-7772 e senha EACD-0972-CA68-05DF
AP 2668 / DF 14 PLATFORMS INC. Em decisão de
16/6/2025, deferi o pedido de WALTER SOUZA BRAGA NETTO e
determinei que a empresa META PLATFORMS encaminhasse, no prazo de
24 (vinte e quatro) horas, as informações complementares requeridas pelo
réu, nas quais estão abrangidas as informações requeridas por JAIR
MESSIAS BOLSONARO. IV. DISPOSITIVO. Diante do exposto, nos termos do
artigo 21, § 1º, do Regimento Interno do SUPREMO TRIBUNAL
FEDERAL, artigo 10 da Lei nº 8.038/90 e dos artigos
400, § 1º, e 402 do Código de Processo Penal:
1) DEFIRO A REALIZAÇÃO DE ACAREAÇÃO, a ser realizada na
sala de audiências do SUPREMO TRIBUNAL FEDERAL no dia 24/6/2025,
entre: 1.A) O réu COLABORADOR MAURO CÉSAR BARBOSA CID e
o réu WALTER SOUZA BRAGA NETTO, as 10h00. O réu
preso WALTER SOUZA BRAGA NETTO deverá comparecer pessoalmente, mediante a
instalação de equipamento de monitoramento eletrônico, devendo se deslocar na
segunda-feira (23/6/2025) e retornar à unidade prisional na terça-feira (24/6/2025),
logo após a acareação, devendo indicar, no prazo de 24
(vinte e quatro) horas, o local onde ficará hospedado e
observar, durante todo o período necessário, a proibição de se
comunicar com qualquer pessoas que não seja seu advogado. Os
réus deverão estar acompanhados de seus advogados. 1.B) O réu
ANDERSON GUSTAVO TORRES e a testemunha MARCO ANTÔNIO FREIRE GOMES,
as Documento assinado digitalmente conforme MP n° 2.200-2/2001 de 24/08/2001.
O documento pode ser acessado pelo endereço http://www.stf.jus.br/portal/autenticacao/autenticarDocumento.asp sob o
código AB3D-1F0C-9157-7772 e senha EACD-0972-CA68-05DF AP 2668 / DF 15
11h00; O réu deverá estar acompanhado de seus advogados. À
testemunha faculta-se a possibilidade de comparecer acompanhada de seu advogado.
DETERMINO, ainda, que, em 48 (quarenta e oito) horas: 2)
O Comandante da Marinha do Brasil, Almirante de Esquadra Marcos
Sampaio Olsen, informe a data em que foi expedida a
Diretiva (Ordem de Movimento) relativa à Operação Formosa 2021, cuja
execução se deu no mês de agosto de 2021; 3)
À empresa Google Brasil (CNPJ: 06.990.590/0001-23, matriz localizada em São
Paulo, na Avenida Brigadeiro Faria Lima), informe os dados do
responsável pela inserção da minuta, que decreta Estado de Defesa,
em domínio público; AUTORIZO, também: 4) A juntada dos documentos
apresentados pela Defesa de PAULO SÉRGIO NOGUEIRA DE OLIVEIRA. 5)
Que a Defesa de ANDERSON GUSTAVO TORRES, no prazo de
5 (cinco) dias, junte aos autos, conforme requerido, EXAMES PERICIAIS
com a finalidade de demonstrar: 5.1) Que o conteúdo da
minuta encontrada na casa de ANDERSON TORRES não tem qualquer
semelhança com os demais documentos supostamente antidemocráticos mencionados durante a
instrução; 5.2) Os dados comparativos entre os trechos do Documento
assinado digitalmente conforme MP n° 2.200-2/2001 de 24/08/2001. O documento
pode ser acessado pelo endereço http://www.stf.jus.br/portal/autenticacao/autenticarDocumento.asp sob o código AB3D-1F0C-9157-7772
e senha EACD-0972-CA68-05DF AP 2668 / DF 16 relatório encaminhado
pela Polícia Federal (e-DOC 611 – páginas 139 e 140,
parte dos itens "1" e "2" do tópico "Considerações e
sugestões"; páginas 99 e 100, parte do item "5" e
a integralidade do item "14" do tópico "Considerações finais"; e
página 128, item "5" do tópico "Considerações e conclusões") e
a live ocorrida em 29/07/2021. Por fim, JULGO PREJUDICADOS o
pedido formulado pelo réu MAURO CÉSAR BARBOSA CID para expedição
de ofício à ABIN – Agência Brasileira de Inteligência e
à à Subsecretaria de Operações Integradas do Distrito Federal, uma
vez que, já se encontram juntado aos autos e os
pedidos formulados pelos réus JAIR MESSIAS BOLSONARO e WALTER SOUZA
BRAGA NETTO para expedição de ofício à empresa META PLATFORMS
INC. para encaminhar informações complementares sobre a conta “@gabrielar702” e/ou
“Gabriela R”, pois anteriormente determinados pelo Juízo. Os demais pedidos,
nos termos do Item I (“Requerimentos protelatórios, irrelevantes ou impertinentes
ao atual momento processual”), estão INDEFERIDOS. Expeça-se o necessário. Intimem-se
os advogados regularmente constituídos. Ciência à Procuradoria-Geral da República. Publique-se.
Brasília, 17 de junho de 2025. Ministro ALEXANDRE DE MORAES
Relator Documento assinado digitalmente Documento assinado digitalmente conforme MP n°
2.200-2/2001 de 24/08/2001. O documento pode ser acessado pelo endereço
http://www.stf.jus.br/portal/autenticacao/autenticarDocumento.asp sob o código AB3D-1F0C-9157-7772 e senha EACD-0972-CA68-05DF

`).then(e => console.log(`Código finalizado, ${e} mensagens enviadas`)).catch(console.error)
